controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      params_file: "/home/sabri/ruben_ws/src/SDRC_PT2/coppelia_controller/config/arm_trajectory_controller.yaml"

    gripper_controller:
      type: position_controllers/GripperActionController
      params_file: "/home/sabri/ruben_ws/src/SDRC_PT2/coppelia_controller/config/gripper_controller.yaml"
